package com.preshan.grocerylist.util

/**
 * Stable logical keys for UI text.
 *
 * The set of keys matches what is listed in `docs/UI_TEXT_KEYS.md`.
 */
enum class AppTextKey(val id: String) {
    // General
    APP_NAME("app_name"),
    CONTINUE("continue"),
    CANCEL("cancel"),
    SAVE("save"),
    DELETE("delete"),
    REMOVE("remove"),
    EDIT("edit"),
    DONE("done"),
    CLOSE("close"),
    YES("yes"),
    NO("no"),
    OK("ok"),
    BACK("back"),
    SEARCH("search"),
    SETTINGS("settings"),
    PRIVACY_POLICY("privacy_policy"),
    APP_VERSION("app_version"),
    SUPPORT_EMAIL("support_email"),
    PLEASE_WAIT("please_wait"),

    // First Launch / Setup
    SETUP_TITLE("setup_title"),
    SETUP_SUBTITLE("setup_subtitle"),
    COUNTRY_REGION("country_region"),
    LANGUAGE("language"),
    SETUP_HELPER("setup_helper"),

    INTERNATIONAL("international"),
    ENGLISH("english"),
    SINHALA("sinhala"),
    TAMIL("tamil"),
    HINDI("hindi"),
    GERMAN("german"),
    FRENCH("french"),
    SPANISH("spanish"),
    ARABIC("arabic"),
    PORTUGUESE("portuguese"),
    INDONESIAN("indonesian"),

    LOCALE_ILLUSTRATION_LINE1("locale_illustration_line1"),
    LOCALE_ILLUSTRATION_LINE2("locale_illustration_line2"),

    // Home
    HOME_TITLE("home_title"),
    HOME_SUBTITLE("home_subtitle"),
    HOME_WELCOME_ILLUSTRATION_CD("home_welcome_illustration_cd"),
    HOME_WELCOME_HEADING("home_welcome_heading"),
    HOME_WELCOME_BODY("home_welcome_body"),
    HOME_SHORTCUTS("home_shortcuts"),
    SHORTCUT_FAVORITES_SUB("shortcut_favorites_sub"),
    SHORTCUT_FREQUENT_SUB("shortcut_frequent_sub"),
    SHORTCUT_MANAGE_SUB("shortcut_manage_sub"),
    SHORTCUT_SETTINGS_SUB("shortcut_settings_sub"),
    HOME_AD_TITLE("home_ad_title"),
    HOME_AD_BADGE("home_ad_badge"),
    PREPARE_SHOPPING_LIST("prepare_shopping_list"),
    FAVORITES("favorites"),
    FREQUENT_ITEMS("frequent_items"),
    MANAGE_ITEMS("manage_items"),
    HOME_AD_PLACEHOLDER("home_ad_placeholder"),
    AD_RESERVED_HELP("ad_reserved_help"),
    CONTINUE_SHOPPING("continue_shopping"),

    // Quick Select
    QUICK_SELECT("quick_select"),
    SEARCH_ITEMS("search_items"),
    CATEGORIES("categories"),
    ALL_CATEGORIES("all_categories"),
    FILTER_BY("filter_by"),
    ALL("all"),
    NONE("none"),
    CLEAR("clear"),
    SELECT_ALL("select_all"),
    DESELECT("deselect"),
    CONFIRM_LIST("confirm_list"),
    SELECTED_ITEMS_COUNT("selected_items_count"),
    NO_ITEMS_FOUND("no_items_found"),
    NO_FAVORITE_ITEMS("no_favorite_items"),
    NO_FREQUENT_ITEMS("no_frequent_items"),

    // Shopping Mode
    SHOPPING_LIST("shopping_list"),
    SHARE("share"),
    SHARE_AS("share_as"),
    SHARE_AS_HELP_TEXT("share_as_help_text"),
    SHARE_CHOOSER_TITLE("share_chooser_title"),
    ALL_ITEMS("all_items"),
    PENDING_ONLY("pending_only"),
    PURCHASED_ONLY("purchased_only"),
    PENDING("pending"),
    PURCHASED("purchased"),
    FINISH_SHOPPING("finish_shopping"),
    COMPLETED_COUNT("completed_count"),
    NOTHING_TO_SHARE("nothing_to_share"),

    // (Not implemented in UI yet, but included in key catalogue)
    FINISH_SHOPPING_CONFIRM_TITLE("finish_shopping_confirm_title"),
    FINISH_SHOPPING_CONFIRM_MESSAGE("finish_shopping_confirm_message"),

    // Manage Items / Editors
    ADD("add"),
    ADD_ITEM("add_item"),
    EDIT_ITEM("edit_item"),
    ITEM_NAME("item_name"),
    CATEGORY("category"),
    FAVORITE("favorite"),
    FAVORITES_QUICK_FILTER_HELP("favorites_quick_filter_help"),
    REMOVE_ITEM("remove_item"),
    REMOVE_ITEM_CONFIRM_TITLE("remove_item_confirm_title"),
    REMOVE_ITEM_CONFIRM_MESSAGE("remove_item_confirm_message"),
    REMOVE_SELECTED_ITEMS_CONFIRM_MESSAGE("remove_selected_items_confirm_message"),
    DUPLICATE_ITEM_MESSAGE("duplicate_item_message"),
    ITEM_NAME_REQUIRED("item_name_required"),
    CATEGORY_REQUIRED("category_required"),
    BULK_ADD("bulk_add"),
    BULK_ADD_TITLE("bulk_add_title"),
    ITEM_NAMES_LABEL("item_names_label"),
    BULK_ADD_HELP_TEXT("bulk_add_help_text"),
    BULK_ADD_HELP_TEXT_DETAILED("bulk_add_help_text_detailed"),
    BULK_ADD_SUCCESS_MESSAGE("bulk_add_success_message"),
    BULK_ADD_SKIPPED_DUPLICATES("bulk_add_skipped_duplicates"),
    BULK_ADD_SKIPPED_EMPTY("bulk_add_skipped_empty"),
    CANCEL_SELECTION("cancel_selection"),
    SELECT_ITEMS_TO_REMOVE("select_items_to_remove"),
    SELECTED_COUNT("selected_count"),

    // Manage Categories
    CATEGORY_NAME_LABEL("category_name_label"),
    REMOVE_CATEGORY_CONFIRM_TITLE("remove_category_confirm_title"),
    REMOVE_CATEGORY_CONFIRM_MESSAGE("remove_category_confirm_message"),
    MANAGE_CATEGORIES_HELP_TEXT("manage_categories_help_text"),
    ADD_CATEGORY("add_category"),
    RENAME_CATEGORY("rename_category"),
    BUILT_IN("built_in"),
    YOUR_CATEGORY("your_category"),
    RENAME("rename"),
    BUILTIN_CATEGORY_CANNOT_REMOVE("builtin_category_cannot_remove"),
    CATEGORY_HAS_ITEMS_CANNOT_REMOVE("category_has_items_cannot_remove"),
    COULD_NOT_REMOVE_CATEGORY("could_not_remove_category"),
    DUPLICATE_CATEGORY_NAME("duplicate_category_name"),
    CATEGORY_NOT_FOUND("category_not_found"),

    // Settings
    CATALOGUE("catalogue"),
    SHOPPING("shopping"),
    DATA("data"),
    PRIVACY("privacy"),
    ABOUT("about"),
    COUNTRY_REGION_LANGUAGE("country_region_language"),
    MANAGE_CATEGORIES("manage_categories"),
    MANAGE_CATEGORIES_SUBTITLE("manage_categories_subtitle"),
    RESTORE("restore"),
    RESTORE_DEFAULT_ITEMS("restore_default_items"),
    RESTORE_DEFAULTS_SUBTITLE("restore_defaults_subtitle"),
    RESET_FREQUENT_ITEM_DATA("reset_frequent_item_data"),
    RESET_FREQUENT_SUBTITLE("reset_frequent_subtitle"),
    CLEAR_CURRENT_SHOPPING_LIST("clear_current_shopping_list"),
    CLEAR_ALL_LOCAL_DATA("clear_all_local_data"),
    CLEAR_ALL_DATA_SUBTITLE("clear_all_data_subtitle"),
    AD_PRIVACY_OPTIONS("ad_privacy_options"),
    PRIVACY_POLICY_SUBTITLE("privacy_policy_subtitle"),
    DEFAULT_GROUPING("default_grouping"),

    RESTORE_DEFAULT_ITEMS_CONFIRM_TITLE("restore_default_items_confirm_title"),
    RESTORE_DEFAULT_ITEMS_CONFIRM_MESSAGE("restore_default_items_confirm_message"),
    RESET_FREQUENT_CONFIRM_TITLE("reset_frequent_confirm_title"),
    RESET_FREQUENT_CONFIRM_MESSAGE("reset_frequent_confirm_message"),
    CLEAR_ALL_DATA_CONFIRM_TITLE("clear_all_data_confirm_title"),
    CLEAR_ALL_DATA_CONFIRM_MESSAGE("clear_all_data_confirm_message"),

    EXPORT_DATA("export_data"),
    IMPORT_DATA("import_data"),
    EXPORT_DATA_SUBTITLE("export_data_subtitle"),
    IMPORT_DATA_SUBTITLE("import_data_subtitle"),
    EXPORT_DATA_MESSAGE("export_data_message"),
    CHOOSE_IMPORT_OPTIONS("choose_import_options"),
    IMPORT_FAVORITES("import_favorites"),
    IMPORT_FREQUENT_DATA("import_frequent_data"),
    IMPORT_REMOVED_ITEMS("import_removed_items"),
    CHOOSE_CSV_FILE("choose_csv_file"),
    SAVE_CSV_FILE("save_csv_file"),
    EXPORT_SUCCESS("export_success"),
    EXPORT_FAILED("export_failed"),
    IMPORT_SUCCESS("import_success"),
    IMPORT_FAILED("import_failed"),
    IMPORT_SUMMARY("import_summary"),
    IMPORT_INVALID_CSV_HEADER("import_invalid_csv_header"),
    IMPORT_EMPTY_FILE("import_empty_file"),
    CATEGORIES_ADDED("categories_added"),
    ITEMS_ADDED("items_added"),
    ITEMS_UPDATED("items_updated"),
    DUPLICATES_SKIPPED("duplicates_skipped"),
    ROWS_FAILED("rows_failed"),

    PRIVACY_TITLE("privacy_title"),
    PRIVACY_INTRO("privacy_intro"),
    PRIVACY_SECTION_HANDLED("privacy_section_handled"),
    PRIVACY_LOCAL_DATA("privacy_local_data"),
    PRIVACY_NO_LOGIN("privacy_no_login"),
    PRIVACY_NO_UPLOAD("privacy_no_upload"),
    PRIVACY_NO_ANALYTICS("privacy_no_analytics"),
    PRIVACY_ADS_FUTURE("privacy_ads_future"),
    PRIVACY_ADS_DATA("privacy_ads_data"),
    PRIVACY_VIEW_ONLINE("privacy_view_online"),
    TERMS_VIEW_ONLINE("terms_view_online"),
    OPEN_IN_BROWSER("open_in_browser"),
    PRIVACY_MANUAL_SHARE("privacy_manual_share"),
    PRIVACY_NO_AUTO_SHARE("privacy_no_auto_share"),
    PRIVACY_MANUAL_IMPORT_EXPORT("privacy_manual_import_export"),
    DEVELOPER_APP_TITLE("developer_app_title"),
    EMAIL("email"),
    PHONE("phone"),
    SEND_EMAIL("send_email"),

    // Category labels (from default seed)
    FOOD_GROCERY("food_grocery"),
    VEGETABLES("vegetables"),
    FRUITS("fruits"),
    MEAT_SHOP("meat_shop"),
    HEALTH_PHARMACY("health_pharmacy"),
    HOUSEHOLD_PERSONAL_CARE("household_personal_care"),

    // Toasts
    TOAST_RESTORE_DEFAULTS_SUMMARY("toast_restore_defaults_summary"),
    TOAST_FREQUENT_RESET("toast_frequent_reset"),
    TOAST_LIST_CLEARED("toast_list_cleared"),
    TOAST_CLEAR_ALL_PLACEHOLDER("toast_clear_all_placeholder"),
    TOAST_CLEAR_ALL_SUCCESS("toast_clear_all_success"),
    TOAST_AD_PRIVACY_PLACEHOLDER("toast_ad_privacy_placeholder"),
    TOAST_STILL_LOADING("toast_still_loading"),
    TOAST_ITEM_NOT_FOUND("toast_item_not_found"),
}

